In [54]:
# create numpy array of shape(5,5) filled with random integers
#  b\w 1&20. Replace all elements in the 3rd column with 1

import numpy as np
array=np.random.randint(1,21,size=(5,5))
print(array)

# array[:,3:4]=1      in 4th column change it to 1

# array[2:3,4]=1            means 2nd row and 4th column = 1
print(array)


[[11  5  2  5 12]
 [18  8 17  1 18]
 [12  2 20  3  1]
 [ 8  4 12  8 16]
 [14 11 13  5  5]]
[[11  5  2  1 12]
 [18  8 17  1 18]
 [12  2 20  1  1]
 [ 8  4 12  1 16]
 [14 11 13  1  5]]


In [62]:
array=np.arange(1,17).reshape((4,4))
print(array)

np.fill_diagonal(array,0)
print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


In [68]:
array=np.arange(1,37).reshape((6,6))
print(array)
print(array[3:5])
print(array[:,2:4])
print(array[3:5,2:4])



[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
[[19 20 21 22 23 24]
 [25 26 27 28 29 30]]
[[ 3  4]
 [ 9 10]
 [15 16]
 [21 22]
 [27 28]
 [33 34]]
[[21 22]
 [27 28]]


In [71]:
array = np.random.randint(1, 21, size=(5, 5))
print(array)
num=np.concatenate((array[0,:],array[-1,:],array[1:-1,0],array[1:-1,-1]))
print(num)

[[ 8 13 11  7 19]
 [ 7 14 16 14 10]
 [19 17 17 15  6]
 [ 8 19  7 11  7]
 [ 7 15  3 16 13]]
[ 8 13 11  7 19  7 15  3 16 13  7 19  8 10  6  7]


In [75]:
arr1=np.random.randint(1,11,size=(3,4)) 
arr2=np.random.randint(1,11,size=(3,4)) 
# print(arr1)
addition=arr1+arr2

[[ 5  8  7  6]
 [10  8  2  6]
 [ 5  4 10  2]]


In [81]:
arr1=np.random.randint(1,11,size=(4,4)) 
arr2=np.random.randint(1,11,size=(4,4)) 
print(f"{arr1} \n {arr2}")
# row_sum=np.sum(arr1,axis=1)
# col_sum=np.sum(arr2,axis=0)



# below is row and column sum
combined_sum=arr1[:,np.newaxis]+arr2
print(combined_sum)


[[ 2  5  6  5]
 [ 9  9  2  4]
 [ 5  8  3  1]
 [ 4  7 10 10]] 
 [[ 1 10  3  7]
 [ 4  5  9  4]
 [ 1  5  2  8]
 [ 5  7  3  3]]
[[[ 3 15  9 12]
  [ 6 10 15  9]
  [ 3 10  8 13]
  [ 7 12  9  8]]

 [[10 19  5 11]
  [13 14 11  8]
  [10 14  4 12]
  [14 16  5  7]]

 [[ 6 18  6  8]
  [ 9 13 12  5]
  [ 6 13  5  9]
  [10 15  6  4]]

 [[ 5 17 13 17]
  [ 8 12 19 14]
  [ 5 12 12 18]
  [ 9 14 13 13]]]


In [92]:
array = np.random.randint(1, 21, size=(5, 5))
print("Original array:")
print(array)

corners=array[[0,0,-1,0],[0,-1,0,-1]]
print(corners)

Original array:
[[ 2  9  1 17 10]
 [ 9  1 11 16 18]
 [ 9  3  7  4 11]
 [11 12  8 14  9]
 [15  1 15 12  1]]
[ 2 10 15 10]


In [106]:
data_type=[('name','U10'),('age','i4'),('weight','f4')]
data=np.array([('Alice',24,55.5),('Bob',34,98)],dtype=data_type)
print(data)
print(data['name'])


[('Alice', 24, 55.5) ('Bob', 34, 98. )]
['Alice' 'Bob']


In [98]:
data_type=[('x','i4'),('y','i4')]
data=np.array([(1,2),(3,4),(5,6)],dtype=data_type)
print(data)
dist=np.sqrt((data['x'][:,np.newaxis] - data['x'])**2 + (data['y'][:,np.newaxis]-data['y'])**2)
print(dist)


[(1, 2) (3, 4) (5, 6)]
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


In [107]:
import numpy.ma as ma

# Create a masked array of shape (4, 4) with random integers
array = np.random.randint(1, 21, size=(4, 4))
masked_array=ma.masked_greater(array,10)
sum_unmasked=masked_array.sum()


In [110]:
array = np.random.randint(1, 21, size=(4, 4))
masked_array=ma.masked_array(array,mask=np.eye(4,dtype=bool))
print(masked_array)

[[-- 6 20 4]
 [18 -- 1 19]
 [3 2 -- 1]
 [3 17 19 --]]
